### ISSUE TITLE
Unit definitions can be changed, fix creates a new problem

### ISSUE THREAD

**Issue by jplatte** [zneak/units-cxx14#5]
Right now `example.cpp` doesn't define units as `const` or `constexpr`. This means that they themselves can't be defined in header files without some ugly tricks, and physical constants can't be either.

There is no direct technical problem with declaring them `constexpr`, which solves the above problem, but there is an indirect problem in it, because now to declare mutable unit variables, you'd have to write `std::remove_const<decltype(_x)>::type` instead of just `decltype(x)`.

I have two ideas on how to fix this:
1. Create macros, something like `CONST_UNIT(u)` and `VAR_UNIT(u)`, that hide `decltype` and `std::remove_const`
2. Don't fix it in the header and instead change the example to create typedefs like `typedef std::remove_const<decltype(_V)>::type voltage`, so the user then has `voltage` and `const voltage` as types.

I'm not sure about 2., it might give the illusion that you can manage different physical dimensions with the same unit with units-cxx14 (distinguish between potential and voltage [both V], or a dimensionless value and an angle [both unitless]). But I can't say I like macros either. What do you think?

**Comment by fay59** [comment]
That's unfortunate.

A third possibility would be to add `typedef quantity var;` in `quantity`, which would allow users to write `decltype(_m * _m)::var` if they plan on mutating the value. `decltype(_m * _m)::var` is shorter than `unordered_map<int, int>` (barely), so it's still acceptable to me (by C++ standards).

A fourth possibility would be to add `template<typename T> using var = std::remove_const<T>::type;`, allowing people to write `var<decltype(_m * _m)>`. It's actually exactly as long as the `::var` syntax, but it has the inconvenient of introducing a new name into the namespace.

That said, `decltype(_N)` is twelve characters; `weight` is six; `auto` is four. In general, the brevity you get from using `auto` is great enough that I think that people will name types only when inference isn't available (fields, parameters) or when they want to make sure that they haven't screwed up.

I think that we shouldn't bother with macros because:
- Already, `decltype(unit)` is a problem only if you need to mutate the value. Multiplications (except with raw numbers) necessarily have a new type, so you can't assign the result back to the same variable; the design promotes immutability/punishes mutability.
- People who look for brevity will be sure to use `auto` or their own typedefs instead of any macro that we come up with, because we can't make a macro that will be short enough, with low-enough potential for conflict.

**Comment by jplatte** [comment]
The third solution sounds good I think.

**Comment by jplatte** [comment]
Also, I forgot to mention in the original issue description: One other big problem with non-const is obviously that they can be redefined, which should certainly not be possible ^^
